package cn.mybatis.mapper;

import cn.mybatis.domain.city;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface cityMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Oct 17 22:08:40 JST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Oct 17 22:08:40 JST 2022
     */
    int insert(city row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Oct 17 22:08:40 JST 2022
     */
    int insertSelective(city row);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Oct 17 22:08:40 JST 2022
     */
    city selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Oct 17 22:08:40 JST 2022
     */
    int updateByPrimaryKeySelective(city row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Oct 17 22:08:40 JST 2022
     */
    int updateByPrimaryKey(city row);
}